/**
 * Prisma ORM configuration (Prisma 6+ config file format).
 *
 * Tells the Prisma CLI where to find the schema, migrations folder, and
 * database connection URL. `dotenv/config` loads `DATABASE_URL` from `.env`
 * when running migrate, generate, or studio commands locally.
 */

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Read from environment — never hardcode credentials here
    url: process.env["DATABASE_URL"],
  },
});
